### ISSUE TITLE
[BUG] SourceGit version 8.26 is not working on MacOS 12.7 for Intel Macs

### ISSUE THREAD

**Issue by ozmium** [sourcegit-scm/sourcegit#372] opened 2024-08-19 09:59 UTC
SourceGit 8.26, released on 19 August 2024 does not launch at all on MacOS 12.7 Monterey, on Intel x86_64 Macs. When you try to open the app, the Finder cannot open it, and it just pops up a dialog that says:

> The application "SourceGit.app" can't be opened. [OK]

<img width="372" alt="SourceGit open app error dialog, from the Finder, 2024-08-19" src="https://github.com/user-attachments/assets/1f3465b2-c749-464e-9e14-d3c65ee72fc7">

There is no other information.

File tested: sourcegit_8.26.osx-x64.zip 

SourceGit 8.25 worked fine.

**Comment by love-linger** [comment] 2024-08-19 10:03
try run `sudo xattr -cr /Applications/SourceGit.app`

**Comment by ozmium** [comment] 2024-08-19 10:14
> try run `sudo xattr -cr /Applications/SourceGit.app`

Thanks for the advice. Could you please give more information about this command? My questions are:

1. Why is this needed?
2. What does it do?
3. Why is this not setup already when the app is downloaded?

**Comment by aikawayataro** [comment] 2024-08-19 10:20
I wonder if we can use bsdtar to keep extended attributes. Can MacOS open these?

**Comment by love-linger** [comment] 2024-08-19 11:10
> try run `sudo xattr -cr /Applications/SourceGit.app`

@ozmium does this works for you?

**Comment by ozmium** [comment] 2024-08-19 11:19
I haven't tried it yet. I'm still a bit confused:

* Why was this command not needed for SourceGit version 8.25?
* Is there a reason why you don't purchase an Apple Developer Certificate and sign it, to avoid this problem on MacOS?

**Comment by love-linger** [comment] 2024-08-19 11:27
> I haven't tried it yet. I'm still a bit confused:
> 
> * Why was this command not needed for SourceGit version 8.25?
> * Is there a reason why you don't purchase an Apple Developer Certificate and sign it, to avoid this problem on MacOS?

I'm not sure why `8.25` works without remove `com.apple.quarantine` flags.
I'm not a macOS/IOS developer. In my daily work, I mainly use Windows and Linux. It is not currently considered to spend $99 per year for this project only.

**Comment by ozmium** [comment] 2024-08-19 12:25
This is a big problem. You probably may not get many users of this app on MacOS because:

* MacOS users will not trust the app, or feel it's secure.
* Mac OS users will not want to override the quarantine feature, or they won't know how to do it.
* MacOS users may not have the administrative permission to override the quarantine feature, so the command may not work for everyone.

You may not realize, but it's a major problem on Apple devices.

I recommend that you setup a Sponsor page, to get user donations and financial support from the community.

You can do it in GitHub:
* Example is here: https://github.com/sponsors/samschott   (Also see his Maestral project page https://github.com/samschott/maestral , which says "Sponsor this project" on the right)
* Another example: https://github.com/sponsors/johanhaleby

Or use an external sponsor. Examples:
* Patreon
* PayPal .me

**Comment by love-linger** [comment] 2024-08-19 12:44
Thank you very much for your advice and I will consider doing so if necessary. 

One of the reasons why I open source this software is that I can't find a _free and fully functional cross-platform_ GIT client. 

Since `git` is a tool usually used by program developers, and the amount of code in this software is not too much (such as the wrappers for git commands under `Commands` folder, which is really simple to understand), at present, if you have concerns about the security of the program, you can check the code yourself and compile it yourself (there is no `com.apple.quarantine` flags if it's built locally).

And I'm not too concerned about the popularity of this software.

**Comment by ozmium** [comment] 2024-08-19 12:54
I've tested running this command many times in the Terminal, and it does not work for me at all.

```
sudo xattr -cr /Applications/SourceGit.app
```

It makes no difference, and the dialog still pops up. However, SourceGit 8.25 continues to work fine.

**Comment by gadfly3173** [comment] 2024-08-19 13:05
I'm not a mac user, but I found this maybe a ci mistake, SourceGit.app may lost execution permission while release. Packaging tar only works on Linux, which may cause the execution permission to be lost when publishing

You can try run this:
```bash
chmod +x "/Applications/SourceGit.app/Contents/MacOS/SourceGit"
```

https://github.com/sourcegit-scm/sourcegit/blob/f3d56ffb204f966936f1005cf4b7abb635194ccf/.github/workflows/ci.yml#L63-L68

**Comment by love-linger** [comment] 2024-08-19 13:10
![image](https://github.com/user-attachments/assets/223d3607-b5b6-4c40-8355-b83564d74d58)

Confirmed. @gadfly3173 is right. It's an issue of exec permission

**Comment by love-linger** [comment] 2024-08-19 13:12
8.25 is packaged manually on my macbook, and 8.26 is packaged using github actions. @aikawayataro would you like to help me correct this?

**Comment by aikawayataro** [comment] 2024-08-19 13:14
Yes, I will
That's my mistake, I could not test the MacOS package

**Comment by love-linger** [comment] 2024-08-19 13:16
> Yes, I will That's my mistake, I could not test the MacOS package

After you create the PR, I'll test it for you

**Comment by love-linger** [comment] 2024-08-20 03:07
closed by PR #373.

**Closed by love-linger** 2024-08-20 03:07 UTC
Labels: need more info

**Comment by love-linger** [comment] 2024-08-20 03:32
@ozmium I've manually re-upload the macOS packages to https://github.com/sourcegit-scm/sourcegit/releases/tag/v8.26

**Comment by ozmium** [comment] 2024-08-20 14:25
Yes, the updated version 8.26 is working for me now, on MacOS 12.7 Monterey.

I did not have to use this command: `sudo xattr -cr /Applications/SourceGit.app`
