### ISSUE TITLE
[BUG] - Can't find repo (Please remove it.)

### ISSUE THREAD

**Issue by ennerperez** [sourcegit-scm/sourcegit#90] opened 2024-04-27 07:25 UTC
In the method FindRepository() `instance.Repositories` returns 0 even when the repo is listed:

![image](https://github.com/sourcegit-scm/sourcegit/assets/1206858/7d7f1f69-13a7-422c-a084-dbd25e68b853)

And it allow to open in file browser and terminal but keep saying:

![image](https://github.com/sourcegit-scm/sourcegit/assets/1206858/24f0ea27-0296-42e1-ae68-8ea80349bf1c)

**Comment by love-linger** [comment] 2024-04-27 11:20
Yes, it's designed that way. Items in the tree in Welcome page should **NOT** be auto-removed. Instead, it must stay where it should be to notice users that they have a invalid repository.

**Comment by ennerperez** [comment] 2024-04-28 04:42
But it's not invalid repository, it was not deleted, I have the last release installed but when I run from source code it's detect the previous repo, but won't let me open because of this, so I have to deleted and adding again which is annoying

IDK if this is a bug in prod, or it's only because of the dual execution.

**Comment by love-linger** [comment] 2024-04-28 04:57
I have reproduced this issue. Here is how I did it:

* Make sure you have closed this app.
* Rename the target repository manually on disk. 
* Open this app, it will check all repositories and remove those not exists on disk.
* Rename the target repository back to it's original name.

It's because `Open In Terminal` and `Open in File Browser` do NOT check repository from `Preference`. Instead, it use the `_id` field directly.

**Comment by love-linger** [comment] 2024-04-28 05:56
Although it is not clear why your repository was emptied from `Preference`, the 32e685622b5373082d10f35eb13c294671c0ea08 will at least alert the user that there is something wrong with this tree node and they should remove it.

**Closed** 2024-04-30 02:21 UTC
Labels: bug

**Comment by ennerperez** [comment] 2024-05-05 19:00
Still reproducible in 8.10 I just update and again I'm getting the error.

![image](https://github.com/sourcegit-scm/sourcegit/assets/1206858/0f7d84eb-ef22-4ebe-8a5b-ee5beb794679)

**Comment by ennerperez** [comment] 2024-05-06 05:02
I think is not enough, I found a workaround to my problem: https://github.com/sourcegit-scm/sourcegit/pull/112
