### ISSUE TITLE
Sometimes "View File Changes" does not change files when the user clicks on another one

### ISSUE THREAD

**Issue by lucerattow** [sourcegit-scm/sourcegit#286] opened 2024-07-26 00:56 UTC
Sometimes "View File Changes" does not change files when the user clicks on another one, this error is temporarily solved when you click on a file inside the staged list

https://github.com/user-attachments/assets/afbf677a-01ac-44e6-b88c-24df65ba0acd

I don't understand when it stops working, but it happens to me often

**Comment by love-linger** [comment] 2024-07-26 02:06
Which version do you use? I can NOT reproduce your issue.

**Comment by lucerattow** [comment] 2024-07-26 03:19
I'm using version 8.22, I checked the releases and I didn't see that this error was corrected in the notes, so I decided to record the error and send it to you while it was happening to me, now I'm using 8.22.1, if it happens to me again I'll comment here

**Comment by love-linger** [comment] 2024-07-26 03:46
Thank you very much. I'll keep this issue open. Look forward to your feedback.

**Comment by love-linger** [comment] 2024-08-14 03:49
Since there has been no further feedback for a long time, close this ISSUE first

**Closed by love-linger** 2024-08-14 03:49 UTC
Labels: need more info
